--- 
title: "GIS Manual"
author: "Francesco Pirotti"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
    bookdown::gitbook:
        includes:
          #in_header: gtag.html
          after_body: footer.html
documentclass: book
description: "A guide to the `lidR` package"
---


# Introduction

`lidR` is an R package for manipulating and visualizating airborne laser scanning (ALS) data with an emphasis on forestry applications. The package is entirely open source and is integrated within the geospatial R ecosytem (i.e. `raster/terra/stars` and `sp/sf`). This guide has been written to help both the ALS novice, as well as seasoned point cloud processing veterans. Key functionality of `lidR` includes functions to:

* Read and write `.las` and `.laz` files and render customized point-cloud display (section \@ref(io))
* Process point clouds including point classification (section \@ref(gnd)),  digital terrain models (section \@ref(dtm)), normalization (section \@ref(norm)) and digital surface models (section \@ref(chm))
* Perform individual tree segmentation (section \@ref(itd-its))
* Compute standard metrics at different levels of regularization (sections \@ref(metrics), \@ref(cba), \@ref(aba), \@ref(tba), \@ref(vba) and \@ref(pba))
* Manage processing for sets of point-cloud files - referred to as a `LAScatalog` (sections \@ref(engine) and \@ref(engine2))
* Guidelines for implementing area-based approaches to forest modelling using ALS data (section \@ref(modeling-aba))
* Facilitate user-defined processing streams for research and development (section \@ref(outbox))
* Understand spatial indexing (section \@ref(spatial-indexing))
* Discover the plugin system (section \@ref(plugins))
